server:
  port: 8071
spring:
  application:
   name: configServer
  profiles:
   # active: native file path location
    active: git
  cloud:
    config:
      server:
        # native:
        # search-locations: "classpath:/config"
        git:
          uri: "https://github.com/sruthy-94/Spring-Config-Server.git"
          default-label: main
          time-out: 5
          clone-on-start: true
          force-pull: true





